/**
 * Worksheet Generator Service
 * Generates interactive worksheets with questions for each subject and difficulty level
 * Question banks are organized by subject and difficulty
 */

import type { WorksheetQuestion, SubjectType, DifficultyLevel } from '../types';

// Question Bank Structure
interface QuestionBank {
  [subject: string]: {
    [difficulty: string]: WorksheetQuestion[];
  };
}

// ===== MATH QUESTIONS =====
const MATH_QUESTIONS: QuestionBank['Math'] = {
  Beginner: [
    { id: 'math_beg_1', subject: 'Math', difficulty: 'Beginner', type: 'multiple-choice', question: 'What is 5 + 3?', options: ['6', '7', '8', '9'], correctAnswer: 2, explanation: '5 + 3 = 8' },
    { id: 'math_beg_2', subject: 'Math', difficulty: 'Beginner', type: 'multiple-choice', question: 'What is 10 - 4?', options: ['4', '5', '6', '7'], correctAnswer: 2, explanation: '10 - 4 = 6' },
    { id: 'math_beg_3', subject: 'Math', difficulty: 'Beginner', type: 'multiple-choice', question: 'What is 2 × 3?', options: ['5', '6', '7', '8'], correctAnswer: 1, explanation: '2 × 3 = 6' },
    { id: 'math_beg_4', subject: 'Math', difficulty: 'Beginner', type: 'multiple-choice', question: 'What is 12 ÷ 4?', options: ['2', '3', '4', '5'], correctAnswer: 1, explanation: '12 ÷ 4 = 3' },
    { id: 'math_beg_5', subject: 'Math', difficulty: 'Beginner', type: 'multiple-choice', question: 'What is 7 + 8?', options: ['13', '14', '15', '16'], correctAnswer: 2, explanation: '7 + 8 = 15' },
    { id: 'math_beg_6', subject: 'Math', difficulty: 'Beginner', type: 'multiple-choice', question: 'What is 20 - 9?', options: ['9', '10', '11', '12'], correctAnswer: 2, explanation: '20 - 9 = 11' },
    { id: 'math_beg_7', subject: 'Math', difficulty: 'Beginner', type: 'multiple-choice', question: 'What is 4 × 5?', options: ['15', '18', '20', '25'], correctAnswer: 2, explanation: '4 × 5 = 20' },
    { id: 'math_beg_8', subject: 'Math', difficulty: 'Beginner', type: 'multiple-choice', question: 'What is 18 ÷ 3?', options: ['4', '5', '6', '7'], correctAnswer: 2, explanation: '18 ÷ 3 = 6' },
    { id: 'math_beg_9', subject: 'Math', difficulty: 'Beginner', type: 'multiple-choice', question: 'What is 9 + 6?', options: ['13', '14', '15', '16'], correctAnswer: 2, explanation: '9 + 6 = 15' },
    { id: 'math_beg_10', subject: 'Math', difficulty: 'Beginner', type: 'multiple-choice', question: 'What is 25 - 10?', options: ['12', '13', '14', '15'], correctAnswer: 3, explanation: '25 - 10 = 15' },
    { id: 'math_beg_11', subject: 'Math', difficulty: 'Beginner', type: 'multiple-choice', question: 'What is 3 × 4?', options: ['10', '11', '12', '13'], correctAnswer: 2, explanation: '3 × 4 = 12' },
    { id: 'math_beg_12', subject: 'Math', difficulty: 'Beginner', type: 'multiple-choice', question: 'What is 16 ÷ 2?', options: ['6', '7', '8', '9'], correctAnswer: 2, explanation: '16 ÷ 2 = 8' },
  ],
  Intermediate: [
    { id: 'math_int_1', subject: 'Math', difficulty: 'Intermediate', type: 'multiple-choice', question: 'What is 15 + 27?', options: ['40', '41', '42', '43'], correctAnswer: 2, explanation: '15 + 27 = 42' },
    { id: 'math_int_2', subject: 'Math', difficulty: 'Intermediate', type: 'multiple-choice', question: 'What is 8 × 7?', options: ['54', '56', '58', '60'], correctAnswer: 1, explanation: '8 × 7 = 56' },
    { id: 'math_int_3', subject: 'Math', difficulty: 'Intermediate', type: 'multiple-choice', question: 'What is 144 ÷ 12?', options: ['10', '11', '12', '13'], correctAnswer: 2, explanation: '144 ÷ 12 = 12' },
    { id: 'math_int_4', subject: 'Math', difficulty: 'Intermediate', type: 'multiple-choice', question: 'What is 25% of 80?', options: ['15', '18', '20', '25'], correctAnswer: 2, explanation: '25% of 80 = 20' },
    { id: 'math_int_5', subject: 'Math', difficulty: 'Intermediate', type: 'multiple-choice', question: 'What is 9 × 9?', options: ['72', '77', '81', '85'], correctAnswer: 2, explanation: '9 × 9 = 81' },
    { id: 'math_int_6', subject: 'Math', difficulty: 'Intermediate', type: 'multiple-choice', question: 'What is 50 - 23?', options: ['25', '26', '27', '28'], correctAnswer: 2, explanation: '50 - 23 = 27' },
    { id: 'math_int_7', subject: 'Math', difficulty: 'Intermediate', type: 'multiple-choice', question: 'What is 6 × 12?', options: ['68', '70', '72', '74'], correctAnswer: 2, explanation: '6 × 12 = 72' },
    { id: 'math_int_8', subject: 'Math', difficulty: 'Intermediate', type: 'multiple-choice', question: 'What is 100 ÷ 25?', options: ['3', '4', '5', '6'], correctAnswer: 1, explanation: '100 ÷ 25 = 4' },
    { id: 'math_int_9', subject: 'Math', difficulty: 'Intermediate', type: 'multiple-choice', question: 'What is 35 + 48?', options: ['81', '82', '83', '84'], correctAnswer: 2, explanation: '35 + 48 = 83' },
    { id: 'math_int_10', subject: 'Math', difficulty: 'Intermediate', type: 'multiple-choice', question: 'What is 11 × 11?', options: ['110', '115', '121', '125'], correctAnswer: 2, explanation: '11 × 11 = 121' },
  ],
  Advanced: [
    { id: 'math_adv_1', subject: 'Math', difficulty: 'Advanced', type: 'multiple-choice', question: 'If x + 5 = 12, what is x?', options: ['5', '6', '7', '8'], correctAnswer: 2, explanation: 'x = 12 - 5 = 7' },
    { id: 'math_adv_2', subject: 'Math', difficulty: 'Advanced', type: 'multiple-choice', question: 'What is 15² (15 squared)?', options: ['200', '215', '225', '235'], correctAnswer: 2, explanation: '15 × 15 = 225' },
    { id: 'math_adv_3', subject: 'Math', difficulty: 'Advanced', type: 'multiple-choice', question: 'What is the area of a rectangle with length 8 and width 5?', options: ['30', '35', '40', '45'], correctAnswer: 2, explanation: 'Area = length × width = 8 × 5 = 40' },
    { id: 'math_adv_4', subject: 'Math', difficulty: 'Advanced', type: 'multiple-choice', question: 'What is 3/4 + 1/4?', options: ['1/2', '3/4', '1', '5/4'], correctAnswer: 2, explanation: '3/4 + 1/4 = 4/4 = 1' },
    { id: 'math_adv_5', subject: 'Math', difficulty: 'Advanced', type: 'multiple-choice', question: 'If 2x = 18, what is x?', options: ['7', '8', '9', '10'], correctAnswer: 2, explanation: 'x = 18 ÷ 2 = 9' },
    { id: 'math_adv_6', subject: 'Math', difficulty: 'Advanced', type: 'multiple-choice', question: 'What is 40% of 150?', options: ['50', '55', '60', '65'], correctAnswer: 2, explanation: '40% of 150 = 0.4 × 150 = 60' },
    { id: 'math_adv_7', subject: 'Math', difficulty: 'Advanced', type: 'multiple-choice', question: 'What is the perimeter of a square with side length 7?', options: ['21', '24', '28', '32'], correctAnswer: 2, explanation: 'Perimeter = 4 × side = 4 × 7 = 28' },
    { id: 'math_adv_8', subject: 'Math', difficulty: 'Advanced', type: 'multiple-choice', question: 'What is √64 (square root of 64)?', options: ['6', '7', '8', '9'], correctAnswer: 2, explanation: '√64 = 8' },
    { id: 'math_adv_9', subject: 'Math', difficulty: 'Advanced', type: 'multiple-choice', question: 'What is 2/5 of 100?', options: ['35', '40', '45', '50'], correctAnswer: 1, explanation: '2/5 × 100 = 40' },
    { id: 'math_adv_10', subject: 'Math', difficulty: 'Advanced', type: 'multiple-choice', question: 'If a triangle has angles of 60° and 60°, what is the third angle?', options: ['50°', '55°', '60°', '70°'], correctAnswer: 2, explanation: 'Sum of angles in a triangle = 180°, so 180 - 60 - 60 = 60°' },
  ],
  Expert: [
    { id: 'math_exp_1', subject: 'Math', difficulty: 'Expert', type: 'multiple-choice', question: 'What is (3x + 5) when x = 4?', options: ['15', '17', '19', '21'], correctAnswer: 1, explanation: '(3 × 4) + 5 = 12 + 5 = 17' },
    { id: 'math_exp_2', subject: 'Math', difficulty: 'Expert', type: 'multiple-choice', question: 'What is the slope of the line y = 3x + 2?', options: ['1', '2', '3', '4'], correctAnswer: 2, explanation: 'In y = mx + b, m is the slope, so slope = 3' },
    { id: 'math_exp_3', subject: 'Math', difficulty: 'Expert', type: 'multiple-choice', question: 'What is 7! (7 factorial) ÷ 5!?', options: ['35', '40', '42', '45'], correctAnswer: 2, explanation: '7!/5! = 7 × 6 = 42' },
    { id: 'math_exp_4', subject: 'Math', difficulty: 'Expert', type: 'multiple-choice', question: 'What is the volume of a cube with side length 3?', options: ['9', '18', '27', '36'], correctAnswer: 2, explanation: 'Volume = side³ = 3³ = 27' },
    { id: 'math_exp_5', subject: 'Math', difficulty: 'Expert', type: 'multiple-choice', question: 'If f(x) = 2x + 3, what is f(5)?', options: ['11', '12', '13', '14'], correctAnswer: 2, explanation: 'f(5) = 2(5) + 3 = 10 + 3 = 13' },
    { id: 'math_exp_6', subject: 'Math', difficulty: 'Expert', type: 'multiple-choice', question: 'What is the circumference of a circle with radius 5? (Use π ≈ 3.14)', options: ['28.4', '29.4', '30.4', '31.4'], correctAnswer: 3, explanation: 'C = 2πr = 2 × 3.14 × 5 = 31.4' },
    { id: 'math_exp_7', subject: 'Math', difficulty: 'Expert', type: 'multiple-choice', question: 'What is 0.75 as a fraction?', options: ['2/3', '3/4', '4/5', '5/6'], correctAnswer: 1, explanation: '0.75 = 75/100 = 3/4' },
    { id: 'math_exp_8', subject: 'Math', difficulty: 'Expert', type: 'multiple-choice', question: 'What is the GCD (Greatest Common Divisor) of 24 and 36?', options: ['6', '8', '12', '18'], correctAnswer: 2, explanation: 'GCD(24, 36) = 12' },
    { id: 'math_exp_9', subject: 'Math', difficulty: 'Expert', type: 'multiple-choice', question: 'If a car travels 60 miles in 45 minutes, what is its speed in mph?', options: ['70 mph', '75 mph', '80 mph', '85 mph'], correctAnswer: 2, explanation: '45 min = 0.75 hours, Speed = 60/0.75 = 80 mph' },
    { id: 'math_exp_10', subject: 'Math', difficulty: 'Expert', type: 'multiple-choice', question: 'What is the sum of the interior angles of a hexagon?', options: ['540°', '600°', '660°', '720°'], correctAnswer: 3, explanation: 'Sum = (n-2) × 180° = (6-2) × 180° = 720°' },
  ],
  Master: [
    { id: 'math_mst_1', subject: 'Math', difficulty: 'Master', type: 'multiple-choice', question: 'If log₂(x) = 5, what is x?', options: ['16', '25', '32', '64'], correctAnswer: 2, explanation: 'log₂(x) = 5 means 2⁵ = x, so x = 32' },
    { id: 'math_mst_2', subject: 'Math', difficulty: 'Master', type: 'multiple-choice', question: 'What is the derivative of f(x) = x²?', options: ['x', '2x', 'x²', '2x²'], correctAnswer: 1, explanation: 'd/dx(x²) = 2x' },
    { id: 'math_mst_3', subject: 'Math', difficulty: 'Master', type: 'multiple-choice', question: 'What is the quadratic formula discriminant for x² + 3x + 2 = 0?', options: ['1', '3', '5', '9'], correctAnswer: 0, explanation: 'Discriminant = b² - 4ac = 9 - 8 = 1' },
    { id: 'math_mst_4', subject: 'Math', difficulty: 'Master', type: 'multiple-choice', question: 'What is sin(30°)?', options: ['0.5', '0.707', '0.866', '1'], correctAnswer: 0, explanation: 'sin(30°) = 1/2 = 0.5' },
    { id: 'math_mst_5', subject: 'Math', difficulty: 'Master', type: 'multiple-choice', question: 'What is the limit of (x² - 1)/(x - 1) as x approaches 1?', options: ['0', '1', '2', 'undefined'], correctAnswer: 2, explanation: 'Factor: (x-1)(x+1)/(x-1) = x+1, as x→1, limit = 2' },
    { id: 'math_mst_6', subject: 'Math', difficulty: 'Master', type: 'multiple-choice', question: 'What is the sum of the series 1 + 1/2 + 1/4 + 1/8 + ...?', options: ['1', '2', '3', '∞'], correctAnswer: 1, explanation: 'Geometric series: S = a/(1-r) = 1/(1-0.5) = 2' },
    { id: 'math_mst_7', subject: 'Math', difficulty: 'Master', type: 'multiple-choice', question: 'What is ∫2x dx (integral of 2x)?', options: ['x', 'x²', 'x² + C', '2x² + C'], correctAnswer: 2, explanation: '∫2x dx = x² + C' },
    { id: 'math_mst_8', subject: 'Math', difficulty: 'Master', type: 'multiple-choice', question: 'What is the probability of rolling two dice and getting a sum of 7?', options: ['1/6', '1/12', '1/18', '1/36'], correctAnswer: 0, explanation: '6 ways out of 36 total outcomes = 6/36 = 1/6' },
    { id: 'math_mst_9', subject: 'Math', difficulty: 'Master', type: 'multiple-choice', question: 'What is the determinant of the matrix [[2, 3], [1, 4]]?', options: ['3', '5', '7', '9'], correctAnswer: 1, explanation: 'det = (2×4) - (3×1) = 8 - 3 = 5' },
    { id: 'math_mst_10', subject: 'Math', difficulty: 'Master', type: 'multiple-choice', question: 'What is e^(ln(5))?', options: ['2', '3', '4', '5'], correctAnswer: 3, explanation: 'e^(ln(x)) = x, so e^(ln(5)) = 5' },
  ],
};

// ===== SCIENCE QUESTIONS =====
const SCIENCE_QUESTIONS: QuestionBank['Science'] = {
  Beginner: [
    { id: 'sci_beg_1', subject: 'Science', difficulty: 'Beginner', type: 'multiple-choice', question: 'What planet is closest to the Sun?', options: ['Venus', 'Mercury', 'Earth', 'Mars'], correctAnswer: 1, explanation: 'Mercury is the closest planet to the Sun' },
    { id: 'sci_beg_2', subject: 'Science', difficulty: 'Beginner', type: 'multiple-choice', question: 'What do plants need to make food?', options: ['Water', 'Sunlight', 'Carbon dioxide', 'All of these'], correctAnswer: 3, explanation: 'Plants need water, sunlight, and CO2 for photosynthesis' },
    { id: 'sci_beg_3', subject: 'Science', difficulty: 'Beginner', type: 'multiple-choice', question: 'How many legs does a spider have?', options: ['6', '8', '10', '12'], correctAnswer: 1, explanation: 'Spiders have 8 legs' },
    { id: 'sci_beg_4', subject: 'Science', difficulty: 'Beginner', type: 'multiple-choice', question: 'What is H2O commonly called?', options: ['Air', 'Water', 'Salt', 'Sugar'], correctAnswer: 1, explanation: 'H2O is the chemical formula for water' },
    { id: 'sci_beg_5', subject: 'Science', difficulty: 'Beginner', type: 'multiple-choice', question: 'What force pulls objects toward Earth?', options: ['Magnetism', 'Friction', 'Gravity', 'Wind'], correctAnswer: 2, explanation: 'Gravity pulls objects toward Earth' },
    { id: 'sci_beg_6', subject: 'Science', difficulty: 'Beginner', type: 'multiple-choice', question: 'What is the largest organ in the human body?', options: ['Heart', 'Brain', 'Liver', 'Skin'], correctAnswer: 3, explanation: 'The skin is the largest organ' },
    { id: 'sci_beg_7', subject: 'Science', difficulty: 'Beginner', type: 'multiple-choice', question: 'What is the center of an atom called?', options: ['Electron', 'Proton', 'Nucleus', 'Neutron'], correctAnswer: 2, explanation: 'The nucleus is the center of an atom' },
    { id: 'sci_beg_8', subject: 'Science', difficulty: 'Beginner', type: 'multiple-choice', question: 'What do we call baby frogs?', options: ['Tadpoles', 'Chicks', 'Cubs', 'Pups'], correctAnswer: 0, explanation: 'Baby frogs are called tadpoles' },
    { id: 'sci_beg_9', subject: 'Science', difficulty: 'Beginner', type: 'multiple-choice', question: 'What gas do humans breathe in?', options: ['Carbon dioxide', 'Helium', 'Oxygen', 'Nitrogen'], correctAnswer: 2, explanation: 'Humans breathe in oxygen' },
    { id: 'sci_beg_10', subject: 'Science', difficulty: 'Beginner', type: 'multiple-choice', question: 'What is the hardest natural substance?', options: ['Gold', 'Iron', 'Diamond', 'Silver'], correctAnswer: 2, explanation: 'Diamond is the hardest natural substance' },
    { id: 'sci_beg_11', subject: 'Science', difficulty: 'Beginner', type: 'multiple-choice', question: 'How many bones do adult humans have?', options: ['186', '206', '226', '246'], correctAnswer: 1, explanation: 'Adults have 206 bones' },
    { id: 'sci_beg_12', subject: 'Science', difficulty: 'Beginner', type: 'multiple-choice', question: 'What causes day and night?', options: ['Moon rotation', 'Earth rotation', 'Sun rotation', 'Star rotation'], correctAnswer: 1, explanation: 'Earth rotation causes day and night' },
  ],
  Intermediate: [
    { id: 'sci_int_1', subject: 'Science', difficulty: 'Intermediate', type: 'multiple-choice', question: 'What is photosynthesis?', options: ['Breaking down food', 'Making food using sunlight', 'Breathing', 'Sleeping'], correctAnswer: 1, explanation: 'Photosynthesis is how plants make food using sunlight' },
    { id: 'sci_int_2', subject: 'Science', difficulty: 'Intermediate', type: 'multiple-choice', question: 'What pH level is neutral?', options: ['5', '7', '9', '11'], correctAnswer: 1, explanation: 'pH 7 is neutral' },
    { id: 'sci_int_3', subject: 'Science', difficulty: 'Intermediate', type: 'multiple-choice', question: 'What is the powerhouse of the cell?', options: ['Nucleus', 'Ribosome', 'Mitochondria', 'Chloroplast'], correctAnswer: 2, explanation: 'Mitochondria is the powerhouse of the cell' },
    { id: 'sci_int_4', subject: 'Science', difficulty: 'Intermediate', type: 'multiple-choice', question: 'What is the speed of light?', options: ['300,000 km/s', '150,000 km/s', '450,000 km/s', '600,000 km/s'], correctAnswer: 0, explanation: 'Light travels at 300,000 km/s' },
    { id: 'sci_int_5', subject: 'Science', difficulty: 'Intermediate', type: 'multiple-choice', question: 'What type of rock is formed from lava?', options: ['Sedimentary', 'Metamorphic', 'Igneous', 'Limestone'], correctAnswer: 2, explanation: 'Igneous rock forms from cooled lava' },
    { id: 'sci_int_6', subject: 'Science', difficulty: 'Intermediate', type: 'multiple-choice', question: 'What is the chemical symbol for Gold?', options: ['Go', 'Au', 'Gd', 'Ag'], correctAnswer: 1, explanation: 'Au is the symbol for Gold (from Latin aurum)' },
    { id: 'sci_int_7', subject: 'Science', difficulty: 'Intermediate', type: 'multiple-choice', question: 'How many chambers does the human heart have?', options: ['2', '3', '4', '5'], correctAnswer: 2, explanation: 'The heart has 4 chambers' },
    { id: 'sci_int_8', subject: 'Science', difficulty: 'Intermediate', type: 'multiple-choice', question: 'What is the largest planet in our solar system?', options: ['Saturn', 'Jupiter', 'Neptune', 'Uranus'], correctAnswer: 1, explanation: 'Jupiter is the largest planet' },
    { id: 'sci_int_9', subject: 'Science', difficulty: 'Intermediate', type: 'multiple-choice', question: 'What is the boiling point of water at sea level?', options: ['90°C', '100°C', '110°C', '120°C'], correctAnswer: 1, explanation: 'Water boils at 100°C at sea level' },
    { id: 'sci_int_10', subject: 'Science', difficulty: 'Intermediate', type: 'multiple-choice', question: 'What organ pumps blood throughout the body?', options: ['Brain', 'Liver', 'Heart', 'Lungs'], correctAnswer: 2, explanation: 'The heart pumps blood' },
  ],
  Advanced: [
    { id: 'sci_adv_1', subject: 'Science', difficulty: 'Advanced', type: 'multiple-choice', question: 'What is the first law of thermodynamics?', options: ['Energy cannot be created or destroyed', 'Every action has a reaction', 'Objects in motion stay in motion', 'Mass is conserved'], correctAnswer: 0, explanation: 'First law: energy cannot be created or destroyed' },
    { id: 'sci_adv_2', subject: 'Science', difficulty: 'Advanced', type: 'multiple-choice', question: 'What is the Avogadro number?', options: ['6.022 × 10²³', '3.14 × 10²³', '9.81 × 10²³', '1.60 × 10²³'], correctAnswer: 0, explanation: 'Avogadro number is 6.022 × 10²³' },
    { id: 'sci_adv_3', subject: 'Science', difficulty: 'Advanced', type: 'multiple-choice', question: 'What is DNA replication?', options: ['Protein synthesis', 'Cell division', 'Copying DNA', 'Energy production'], correctAnswer: 2, explanation: 'DNA replication is the process of copying DNA' },
    { id: 'sci_adv_4', subject: 'Science', difficulty: 'Advanced', type: 'multiple-choice', question: 'What is the noble gas in the second period?', options: ['Helium', 'Neon', 'Argon', 'Krypton'], correctAnswer: 1, explanation: 'Neon is the noble gas in period 2' },
    { id: 'sci_adv_5', subject: 'Science', difficulty: 'Advanced', type: 'multiple-choice', question: 'What is the study of fungi called?', options: ['Botany', 'Mycology', 'Zoology', 'Geology'], correctAnswer: 1, explanation: 'Mycology is the study of fungi' },
    { id: 'sci_adv_6', subject: 'Science', difficulty: 'Advanced', type: 'multiple-choice', question: 'What is the process of cell division called?', options: ['Meiosis', 'Mitosis', 'Both', 'Neither'], correctAnswer: 2, explanation: 'Both mitosis and meiosis are cell division processes' },
    { id: 'sci_adv_7', subject: 'Science', difficulty: 'Advanced', type: 'multiple-choice', question: 'What is the SI unit of force?', options: ['Joule', 'Newton', 'Watt', 'Pascal'], correctAnswer: 1, explanation: 'Newton is the SI unit of force' },
    { id: 'sci_adv_8', subject: 'Science', difficulty: 'Advanced', type: 'multiple-choice', question: 'What is the atomic number of Carbon?', options: ['4', '5', '6', '7'], correctAnswer: 2, explanation: 'Carbon has atomic number 6' },
    { id: 'sci_adv_9', subject: 'Science', difficulty: 'Advanced', type: 'multiple-choice', question: 'What is the function of chlorophyll?', options: ['Store energy', 'Absorb light', 'Break down food', 'Transport water'], correctAnswer: 1, explanation: 'Chlorophyll absorbs light for photosynthesis' },
    { id: 'sci_adv_10', subject: 'Science', difficulty: 'Advanced', type: 'multiple-choice', question: 'What is the half-life?', options: ['Time for half atoms to decay', 'Time for reaction to complete', 'Time for temperature to halve', 'Time for pressure to halve'], correctAnswer: 0, explanation: 'Half-life is time for half of radioactive atoms to decay' },
  ],
  Expert: [
    { id: 'sci_exp_1', subject: 'Science', difficulty: 'Expert', type: 'multiple-choice', question: 'What is the Heisenberg Uncertainty Principle?', options: ['Position and momentum cannot be precisely known simultaneously', 'Energy is quantized', 'Light behaves as a wave and particle', 'Matter cannot be created'], correctAnswer: 0, explanation: 'Heisenberg principle: cannot know position and momentum precisely at same time' },
    { id: 'sci_exp_2', subject: 'Science', difficulty: 'Expert', type: 'multiple-choice', question: 'What is the Krebs cycle?', options: ['DNA replication', 'Protein synthesis', 'Cellular respiration', 'Photosynthesis'], correctAnswer: 2, explanation: 'Krebs cycle is part of cellular respiration' },
    { id: 'sci_exp_3', subject: 'Science', difficulty: 'Expert', type: 'multiple-choice', question: 'What is an enzyme?', options: ['A hormone', 'A protein catalyst', 'A lipid', 'A carbohydrate'], correctAnswer: 1, explanation: 'Enzymes are protein catalysts' },
    { id: 'sci_exp_4', subject: 'Science', difficulty: 'Expert', type: 'multiple-choice', question: 'What is the strongest type of chemical bond?', options: ['Ionic', 'Covalent', 'Hydrogen', 'Van der Waals'], correctAnswer: 1, explanation: 'Covalent bonds are generally strongest' },
    { id: 'sci_exp_5', subject: 'Science', difficulty: 'Expert', type: 'multiple-choice', question: 'What is Ohm\'s Law?', options: ['V = IR', 'F = ma', 'E = mc²', 'P = IV'], correctAnswer: 0, explanation: 'Ohm\'s Law is V = IR (Voltage = Current × Resistance)' },
    { id: 'sci_exp_6', subject: 'Science', difficulty: 'Expert', type: 'multiple-choice', question: 'What is transcription in biology?', options: ['DNA to DNA', 'DNA to RNA', 'RNA to Protein', 'Protein to DNA'], correctAnswer: 1, explanation: 'Transcription converts DNA to RNA' },
    { id: 'sci_exp_7', subject: 'Science', difficulty: 'Expert', type: 'multiple-choice', question: 'What is the electron configuration of Oxygen?', options: ['1s² 2s² 2p⁴', '1s² 2s² 2p⁶', '1s² 2s² 2p²', '1s² 2s² 2p³'], correctAnswer: 0, explanation: 'Oxygen: 1s² 2s² 2p⁴' },
    { id: 'sci_exp_8', subject: 'Science', difficulty: 'Expert', type: 'multiple-choice', question: 'What is entropy?', options: ['Energy', 'Order', 'Disorder', 'Temperature'], correctAnswer: 2, explanation: 'Entropy is a measure of disorder' },
    { id: 'sci_exp_9', subject: 'Science', difficulty: 'Expert', type: 'multiple-choice', question: 'What is the Doppler effect?', options: ['Change in frequency due to motion', 'Bending of light', 'Splitting of light', 'Reflection of sound'], correctAnswer: 0, explanation: 'Doppler effect: frequency change due to relative motion' },
    { id: 'sci_exp_10', subject: 'Science', difficulty: 'Expert', type: 'multiple-choice', question: 'What is a peptide bond?', options: ['Bond between amino acids', 'Bond between nucleotides', 'Bond between lipids', 'Bond between sugars'], correctAnswer: 0, explanation: 'Peptide bonds link amino acids in proteins' },
  ],
  Master: [
    { id: 'sci_mst_1', subject: 'Science', difficulty: 'Master', type: 'multiple-choice', question: 'What is the Schrödinger equation used for?', options: ['Classical mechanics', 'Quantum mechanics', 'Thermodynamics', 'Relativity'], correctAnswer: 1, explanation: 'Schrödinger equation describes quantum systems' },
    { id: 'sci_mst_2', subject: 'Science', difficulty: 'Master', type: 'multiple-choice', question: 'What is PCR in molecular biology?', options: ['Protein Chain Reaction', 'Polymerase Chain Reaction', 'Peptide Chain Reaction', 'Polymer Chain Reaction'], correctAnswer: 1, explanation: 'PCR stands for Polymerase Chain Reaction' },
    { id: 'sci_mst_3', subject: 'Science', difficulty: 'Master', type: 'multiple-choice', question: 'What is the Pauli Exclusion Principle?', options: ['No two electrons can have the same quantum state', 'Energy is quantized', 'Momentum is conserved', 'Charge is conserved'], correctAnswer: 0, explanation: 'Pauli principle: no two electrons can have same quantum numbers' },
    { id: 'sci_mst_4', subject: 'Science', difficulty: 'Master', type: 'multiple-choice', question: 'What is oxidative phosphorylation?', options: ['ATP synthesis in chloroplasts', 'ATP synthesis in mitochondria', 'Glucose breakdown', 'Fatty acid synthesis'], correctAnswer: 1, explanation: 'Oxidative phosphorylation produces ATP in mitochondria' },
    { id: 'sci_mst_5', subject: 'Science', difficulty: 'Master', type: 'multiple-choice', question: 'What is the mechanism of SN2 reaction?', options: ['Two-step substitution', 'One-step substitution', 'Elimination', 'Addition'], correctAnswer: 1, explanation: 'SN2 is a one-step nucleophilic substitution' },
    { id: 'sci_mst_6', subject: 'Science', difficulty: 'Master', type: 'multiple-choice', question: 'What is the Hardy-Weinberg principle?', options: ['Genetic equilibrium in populations', 'Natural selection', 'Mutation rate', 'Gene flow'], correctAnswer: 0, explanation: 'Hardy-Weinberg describes genetic equilibrium' },
    { id: 'sci_mst_7', subject: 'Science', difficulty: 'Master', type: 'multiple-choice', question: 'What is the standard Gibbs free energy change (ΔG°) for a spontaneous reaction?', options: ['Positive', 'Negative', 'Zero', 'Infinite'], correctAnswer: 1, explanation: 'Spontaneous reactions have negative ΔG°' },
    { id: 'sci_mst_8', subject: 'Science', difficulty: 'Master', type: 'multiple-choice', question: 'What is the central dogma of molecular biology?', options: ['DNA → RNA → Protein', 'Protein → RNA → DNA', 'RNA → DNA → Protein', 'DNA → Protein → RNA'], correctAnswer: 0, explanation: 'Central dogma: DNA → RNA → Protein' },
    { id: 'sci_mst_9', subject: 'Science', difficulty: 'Master', type: 'multiple-choice', question: 'What is the Compton effect?', options: ['Change in X-ray wavelength after scattering', 'Photoelectric effect', 'Interference', 'Diffraction'], correctAnswer: 0, explanation: 'Compton effect: X-ray wavelength change after scattering' },
    { id: 'sci_mst_10', subject: 'Science', difficulty: 'Master', type: 'multiple-choice', question: 'What is a ligand in coordination chemistry?', options: ['Metal ion', 'Electron donor', 'Proton', 'Neutron'], correctAnswer: 1, explanation: 'Ligands are electron donors that bind to metal ions' },
  ],
};

// ===== HISTORY QUESTIONS =====
const HISTORY_QUESTIONS: QuestionBank['History'] = {
  Beginner: [
    { id: 'hist_beg_1', subject: 'History', difficulty: 'Beginner', type: 'multiple-choice', question: 'Who was the first president of the United States?', options: ['Thomas Jefferson', 'George Washington', 'Benjamin Franklin', 'John Adams'], correctAnswer: 1, explanation: 'George Washington was the first US president' },
    { id: 'hist_beg_2', subject: 'History', difficulty: 'Beginner', type: 'multiple-choice', question: 'In what year did Christopher Columbus sail to America?', options: ['1492', '1500', '1520', '1450'], correctAnswer: 0, explanation: 'Columbus sailed in 1492' },
    { id: 'hist_beg_3', subject: 'History', difficulty: 'Beginner', type: 'multiple-choice', question: 'What country built the Great Wall?', options: ['Japan', 'Korea', 'China', 'India'], correctAnswer: 2, explanation: 'China built the Great Wall' },
    { id: 'hist_beg_4', subject: 'History', difficulty: 'Beginner', type: 'multiple-choice', question: 'Who wrote the Declaration of Independence?', options: ['George Washington', 'Benjamin Franklin', 'Thomas Jefferson', 'John Adams'], correctAnswer: 2, explanation: 'Thomas Jefferson wrote the Declaration of Independence' },
    { id: 'hist_beg_5', subject: 'History', difficulty: 'Beginner', type: 'multiple-choice', question: 'What were the ancient Egyptian rulers called?', options: ['Kings', 'Emperors', 'Pharaohs', 'Sultans'], correctAnswer: 2, explanation: 'Egyptian rulers were called Pharaohs' },
    { id: 'hist_beg_6', subject: 'History', difficulty: 'Beginner', type: 'multiple-choice', question: 'Which war was fought between the North and South in America?', options: ['Revolutionary War', 'Civil War', 'World War I', 'War of 1812'], correctAnswer: 1, explanation: 'The Civil War was fought between North and South' },
    { id: 'hist_beg_7', subject: 'History', difficulty: 'Beginner', type: 'multiple-choice', question: 'What ship did the Pilgrims sail to America?', options: ['Santa Maria', 'Mayflower', 'Titanic', 'Niña'], correctAnswer: 1, explanation: 'The Pilgrims sailed on the Mayflower' },
    { id: 'hist_beg_8', subject: 'History', difficulty: 'Beginner', type: 'multiple-choice', question: 'Who invented the light bulb?', options: ['Nikola Tesla', 'Benjamin Franklin', 'Thomas Edison', 'Alexander Bell'], correctAnswer: 2, explanation: 'Thomas Edison invented the practical light bulb' },
    { id: 'hist_beg_9', subject: 'History', difficulty: 'Beginner', type: 'multiple-choice', question: 'What year did World War II end?', options: ['1943', '1944', '1945', '1946'], correctAnswer: 2, explanation: 'World War II ended in 1945' },
    { id: 'hist_beg_10', subject: 'History', difficulty: 'Beginner', type: 'multiple-choice', question: 'Who was the first man on the moon?', options: ['Buzz Aldrin', 'Neil Armstrong', 'John Glenn', 'Yuri Gagarin'], correctAnswer: 1, explanation: 'Neil Armstrong was first on the moon' },
    { id: 'hist_beg_11', subject: 'History', difficulty: 'Beginner', type: 'multiple-choice', question: 'What empire built the Colosseum?', options: ['Greek', 'Persian', 'Roman', 'Egyptian'], correctAnswer: 2, explanation: 'The Romans built the Colosseum' },
    { id: 'hist_beg_12', subject: 'History', difficulty: 'Beginner', type: 'multiple-choice', question: 'In what year did America gain independence?', options: ['1776', '1781', '1789', '1800'], correctAnswer: 0, explanation: 'America declared independence in 1776' },
  ],
  Intermediate: [
    { id: 'hist_int_1', subject: 'History', difficulty: 'Intermediate', type: 'multiple-choice', question: 'What was the Renaissance?', options: ['A war', 'A cultural rebirth', 'A plague', 'A revolution'], correctAnswer: 1, explanation: 'The Renaissance was a cultural rebirth in Europe' },
    { id: 'hist_int_2', subject: 'History', difficulty: 'Intermediate', type: 'multiple-choice', question: 'Who led India to independence from Britain?', options: ['Jawaharlal Nehru', 'Mahatma Gandhi', 'Muhammad Ali Jinnah', 'Subhas Bose'], correctAnswer: 1, explanation: 'Mahatma Gandhi led India\'s independence movement' },
    { id: 'hist_int_3', subject: 'History', difficulty: 'Intermediate', type: 'multiple-choice', question: 'What was the Cold War?', options: ['A winter war', 'A war in Antarctica', 'A political standoff', 'A trade war'], correctAnswer: 2, explanation: 'The Cold War was a political/ideological standoff between USA and USSR' },
    { id: 'hist_int_4', subject: 'History', difficulty: 'Intermediate', type: 'multiple-choice', question: 'Who was Martin Luther?', options: ['Civil rights leader', 'Protestant reformer', 'Scientist', 'Explorer'], correctAnswer: 1, explanation: 'Martin Luther started the Protestant Reformation' },
    { id: 'hist_int_5', subject: 'History', difficulty: 'Intermediate', type: 'multiple-choice', question: 'What was the Magna Carta?', options: ['A ship', 'A legal document', 'A battle', 'A king'], correctAnswer: 1, explanation: 'The Magna Carta limited royal power in England' },
    { id: 'hist_int_6', subject: 'History', difficulty: 'Intermediate', type: 'multiple-choice', question: 'What empire did Julius Caesar lead?', options: ['Greek', 'Roman', 'Persian', 'Macedonian'], correctAnswer: 1, explanation: 'Julius Caesar was a Roman leader' },
    { id: 'hist_int_7', subject: 'History', difficulty: 'Intermediate', type: 'multiple-choice', question: 'What was the Industrial Revolution?', options: ['A war', 'A shift to machine manufacturing', 'A disease outbreak', 'A religious movement'], correctAnswer: 1, explanation: 'Industrial Revolution was the shift to machine manufacturing' },
    { id: 'hist_int_8', subject: 'History', difficulty: 'Intermediate', type: 'multiple-choice', question: 'Who painted the Mona Lisa?', options: ['Michelangelo', 'Leonardo da Vinci', 'Raphael', 'Donatello'], correctAnswer: 1, explanation: 'Leonardo da Vinci painted the Mona Lisa' },
    { id: 'hist_int_9', subject: 'History', difficulty: 'Intermediate', type: 'multiple-choice', question: 'What year did the Berlin Wall fall?', options: ['1987', '1989', '1991', '1993'], correctAnswer: 1, explanation: 'The Berlin Wall fell in 1989' },
    { id: 'hist_int_10', subject: 'History', difficulty: 'Intermediate', type: 'multiple-choice', question: 'Who discovered America for Europe?', options: ['Leif Erikson', 'Christopher Columbus', 'Both', 'Neither'], correctAnswer: 2, explanation: 'Leif Erikson arrived first, Columbus made it known to Europe' },
  ],
  Advanced: [
    { id: 'hist_adv_1', subject: 'History', difficulty: 'Advanced', type: 'multiple-choice', question: 'What was the Treaty of Versailles?', options: ['Treaty ending WWI', 'Treaty ending WWII', 'Treaty ending Civil War', 'Treaty of independence'], correctAnswer: 0, explanation: 'Treaty of Versailles ended World War I' },
    { id: 'hist_adv_2', subject: 'History', difficulty: 'Advanced', type: 'multiple-choice', question: 'What was the Silk Road?', options: ['A highway', 'Trade routes', 'A railroad', 'A sea route'], correctAnswer: 1, explanation: 'The Silk Road was a network of trade routes' },
    { id: 'hist_adv_3', subject: 'History', difficulty: 'Advanced', type: 'multiple-choice', question: 'Who was Genghis Khan?', options: ['Chinese emperor', 'Mongol conqueror', 'Japanese shogun', 'Indian emperor'], correctAnswer: 1, explanation: 'Genghis Khan founded the Mongol Empire' },
    { id: 'hist_adv_4', subject: 'History', difficulty: 'Advanced', type: 'multiple-choice', question: 'What was the Enlightenment?', options: ['Religious movement', 'Intellectual movement', 'Military campaign', 'Economic policy'], correctAnswer: 1, explanation: 'The Enlightenment was an intellectual movement emphasizing reason' },
    { id: 'hist_adv_5', subject: 'History', difficulty: 'Advanced', type: 'multiple-choice', question: 'What caused the French Revolution?', options: ['Invasion', 'Economic crisis and inequality', 'Religious conflict', 'Natural disaster'], correctAnswer: 1, explanation: 'Economic crisis and social inequality sparked the French Revolution' },
    { id: 'hist_adv_6', subject: 'History', difficulty: 'Advanced', type: 'multiple-choice', question: 'Who was Alexander the Great?', options: ['Roman general', 'Greek king', 'Egyptian pharaoh', 'Persian emperor'], correctAnswer: 1, explanation: 'Alexander the Great was a Greek king who conquered much of Asia' },
    { id: 'hist_adv_7', subject: 'History', difficulty: 'Advanced', type: 'multiple-choice', question: 'What was the Manhattan Project?', options: ['Building project', 'Atomic bomb development', 'Space program', 'Economic plan'], correctAnswer: 1, explanation: 'Manhattan Project developed the atomic bomb' },
    { id: 'hist_adv_8', subject: 'History', difficulty: 'Advanced', type: 'multiple-choice', question: 'What was the Black Death?', options: ['War', 'Plague pandemic', 'Famine', 'Earthquake'], correctAnswer: 1, explanation: 'The Black Death was a devastating plague pandemic' },
    { id: 'hist_adv_9', subject: 'History', difficulty: 'Advanced', type: 'multiple-choice', question: 'Who was Cleopatra?', options: ['Greek queen', 'Roman empress', 'Egyptian pharaoh', 'Persian ruler'], correctAnswer: 2, explanation: 'Cleopatra was the last pharaoh of Egypt' },
    { id: 'hist_adv_10', subject: 'History', difficulty: 'Advanced', type: 'multiple-choice', question: 'What was the Louisiana Purchase?', options: ['A company', 'Land bought from France', 'A trade agreement', 'A war victory'], correctAnswer: 1, explanation: 'The Louisiana Purchase doubled US territory, bought from France' },
  ],
  Expert: [
    { id: 'hist_exp_1', subject: 'History', difficulty: 'Expert', type: 'multiple-choice', question: 'What was the Thirty Years\' War?', options: ['Religious conflict in Europe', 'War in Asia', 'Civil war in America', 'Colonial war'], correctAnswer: 0, explanation: 'The Thirty Years\' War was a religious conflict in Europe (1618-1648)' },
    { id: 'hist_exp_2', subject: 'History', difficulty: 'Expert', type: 'multiple-choice', question: 'What was mercantilism?', options: ['A religion', 'An economic policy', 'A political system', 'A military strategy'], correctAnswer: 1, explanation: 'Mercantilism was an economic policy promoting exports over imports' },
    { id: 'hist_exp_3', subject: 'History', difficulty: 'Expert', type: 'multiple-choice', question: 'Who was Hammurabi?', options: ['Egyptian pharaoh', 'Babylonian king', 'Greek philosopher', 'Roman senator'], correctAnswer: 1, explanation: 'Hammurabi was a Babylonian king known for his law code' },
    { id: 'hist_exp_4', subject: 'History', difficulty: 'Expert', type: 'multiple-choice', question: 'What was the Congress of Vienna?', options: ['Peace conference after Napoleon', 'Declaration of war', 'Economic summit', 'Religious council'], correctAnswer: 0, explanation: 'Congress of Vienna reorganized Europe after Napoleon\'s defeat' },
    { id: 'hist_exp_5', subject: 'History', difficulty: 'Expert', type: 'multiple-choice', question: 'What was the Meiji Restoration?', options: ['Chinese reform', 'Japanese modernization', 'Korean independence', 'Indian uprising'], correctAnswer: 1, explanation: 'Meiji Restoration was Japan\'s rapid modernization' },
    { id: 'hist_exp_6', subject: 'History', difficulty: 'Expert', type: 'multiple-choice', question: 'What was the Peloponnesian War?', options: ['Athens vs Sparta', 'Rome vs Carthage', 'Persia vs Greece', 'Egypt vs Hittites'], correctAnswer: 0, explanation: 'Peloponnesian War was between Athens and Sparta' },
    { id: 'hist_exp_7', subject: 'History', difficulty: 'Expert', type: 'multiple-choice', question: 'What was the Scramble for Africa?', options: ['African independence', 'European colonization', 'African civil wars', 'Slave trade'], correctAnswer: 1, explanation: 'Scramble for Africa was European colonization in late 1800s' },
    { id: 'hist_exp_8', subject: 'History', difficulty: 'Expert', type: 'multiple-choice', question: 'What was the Boxer Rebellion?', options: ['Uprising in China', 'Japanese revolt', 'Indian mutiny', 'Korean independence'], correctAnswer: 0, explanation: 'Boxer Rebellion was an anti-foreign uprising in China (1899-1901)' },
    { id: 'hist_exp_9', subject: 'History', difficulty: 'Expert', type: 'multiple-choice', question: 'What was the Weimar Republic?', options: ['Austrian government', 'German government 1919-1933', 'Swiss government', 'Italian government'], correctAnswer: 1, explanation: 'Weimar Republic was Germany\'s government between WWI and WWII' },
    { id: 'hist_exp_10', subject: 'History', difficulty: 'Expert', type: 'multiple-choice', question: 'What was the Zimmermann Telegram?', options: ['Peace offer', 'German proposal to Mexico', 'Declaration of war', 'Trade agreement'], correctAnswer: 1, explanation: 'Zimmermann Telegram was Germany\'s proposal for Mexico to attack the US' },
  ],
  Master: [
    { id: 'hist_mst_1', subject: 'History', difficulty: 'Master', type: 'multiple-choice', question: 'What was the Peace of Westphalia?', options: ['Treaty ending Thirty Years\' War', 'Treaty ending WWI', 'Treaty ending Napoleonic Wars', 'Treaty ending WWII'], correctAnswer: 0, explanation: 'Peace of Westphalia ended the Thirty Years\' War (1648)' },
    { id: 'hist_mst_2', subject: 'History', difficulty: 'Master', type: 'multiple-choice', question: 'What was the Investiture Controversy?', options: ['Conflict over appointing bishops', 'Dispute over land', 'Economic disagreement', 'Military conflict'], correctAnswer: 0, explanation: 'Investiture Controversy was about power to appoint bishops' },
    { id: 'hist_mst_3', subject: 'History', difficulty: 'Master', type: 'multiple-choice', question: 'What was the Great Schism of 1054?', options: ['Protestant Reformation', 'Split between Catholic and Orthodox', 'Islamic split', 'Buddhist division'], correctAnswer: 1, explanation: 'Great Schism split Christianity into Catholic and Orthodox' },
    { id: 'hist_mst_4', subject: 'History', difficulty: 'Master', type: 'multiple-choice', question: 'What was the Defenestration of Prague?', options: ['Treaty signing', 'Throwing officials from window', 'Battle', 'Coronation'], correctAnswer: 1, explanation: 'Defenestration of Prague sparked Thirty Years\' War by throwing officials from window' },
    { id: 'hist_mst_5', subject: 'History', difficulty: 'Master', type: 'multiple-choice', question: 'What was the Edict of Nantes?', options: ['Religious tolerance decree', 'Declaration of war', 'Economic policy', 'Legal code'], correctAnswer: 0, explanation: 'Edict of Nantes granted religious tolerance to Huguenots in France' },
    { id: 'hist_mst_6', subject: 'History', difficulty: 'Master', type: 'multiple-choice', question: 'What was the Council of Trent?', options: ['Protestant council', 'Catholic response to Reformation', 'Orthodox synod', 'Political assembly'], correctAnswer: 1, explanation: 'Council of Trent was Catholic Church\'s response to Protestant Reformation' },
    { id: 'hist_mst_7', subject: 'History', difficulty: 'Master', type: 'multiple-choice', question: 'What was the Sykes-Picot Agreement?', options: ['Peace treaty', 'Secret plan to divide Middle East', 'Trade agreement', 'Alliance'], correctAnswer: 1, explanation: 'Sykes-Picot Agreement divided Middle East between Britain and France' },
    { id: 'hist_mst_8', subject: 'History', difficulty: 'Master', type: 'multiple-choice', question: 'What was the Glorious Revolution?', options: ['French revolution', 'English bloodless revolution', 'American revolution', 'Russian revolution'], correctAnswer: 1, explanation: 'Glorious Revolution (1688) was England\'s bloodless transfer of power' },
    { id: 'hist_mst_9', subject: 'History', difficulty: 'Master', type: 'multiple-choice', question: 'What was the Carolingian Renaissance?', options: ['Italian cultural rebirth', 'French cultural revival', 'German artistic movement', 'Spanish golden age'], correctAnswer: 1, explanation: 'Carolingian Renaissance was cultural revival under Charlemagne' },
    { id: 'hist_mst_10', subject: 'History', difficulty: 'Master', type: 'multiple-choice', question: 'What was the Fourth Crusade\'s outcome?', options: ['Captured Jerusalem', 'Sacked Constantinople', 'Defeated by Muslims', 'Made peace treaty'], correctAnswer: 1, explanation: 'Fourth Crusade infamously sacked Constantinople instead of reaching Jerusalem' },
  ],
};

// ===== BIBLE QUESTIONS =====
const BIBLE_QUESTIONS: QuestionBank['Bible'] = {
  Beginner: [
    { id: 'bible_beg_1', subject: 'Bible', difficulty: 'Beginner', type: 'multiple-choice', question: 'Who built the ark?', options: ['Moses', 'Noah', 'Abraham', 'David'], correctAnswer: 1, explanation: 'Noah built the ark' },
    { id: 'bible_beg_2', subject: 'Bible', difficulty: 'Beginner', type: 'multiple-choice', question: 'How many days did God take to create the world?', options: ['5', '6', '7', '8'], correctAnswer: 1, explanation: 'God created the world in 6 days and rested on the 7th' },
    { id: 'bible_beg_3', subject: 'Bible', difficulty: 'Beginner', type: 'multiple-choice', question: 'Who was swallowed by a big fish?', options: ['Jonah', 'Job', 'Joshua', 'Joseph'], correctAnswer: 0, explanation: 'Jonah was swallowed by a big fish' },
    { id: 'bible_beg_4', subject: 'Bible', difficulty: 'Beginner', type: 'multiple-choice', question: 'Who was the first man?', options: ['Abraham', 'Adam', 'Moses', 'David'], correctAnswer: 1, explanation: 'Adam was the first man' },
    { id: 'bible_beg_5', subject: 'Bible', difficulty: 'Beginner', type: 'multiple-choice', question: 'Who defeated Goliath?', options: ['Saul', 'David', 'Solomon', 'Samuel'], correctAnswer: 1, explanation: 'David defeated Goliath with a sling' },
    { id: 'bible_beg_6', subject: 'Bible', difficulty: 'Beginner', type: 'multiple-choice', question: 'How many apostles did Jesus have?', options: ['10', '11', '12', '13'], correctAnswer: 2, explanation: 'Jesus had 12 apostles' },
    { id: 'bible_beg_7', subject: 'Bible', difficulty: 'Beginner', type: 'multiple-choice', question: 'Who was Moses\' brother?', options: ['Aaron', 'Abraham', 'Isaac', 'Jacob'], correctAnswer: 0, explanation: 'Aaron was Moses\' brother' },
    { id: 'bible_beg_8', subject: 'Bible', difficulty: 'Beginner', type: 'multiple-choice', question: 'What did Jesus turn water into?', options: ['Oil', 'Wine', 'Milk', 'Juice'], correctAnswer: 1, explanation: 'Jesus turned water into wine at Cana' },
    { id: 'bible_beg_9', subject: 'Bible', difficulty: 'Beginner', type: 'multiple-choice', question: 'Who betrayed Jesus?', options: ['Peter', 'John', 'Judas', 'James'], correctAnswer: 2, explanation: 'Judas Iscariot betrayed Jesus' },
    { id: 'bible_beg_10', subject: 'Bible', difficulty: 'Beginner', type: 'multiple-choice', question: 'In what town was Jesus born?', options: ['Nazareth', 'Jerusalem', 'Bethlehem', 'Galilee'], correctAnswer: 2, explanation: 'Jesus was born in Bethlehem' },
    { id: 'bible_beg_11', subject: 'Bible', difficulty: 'Beginner', type: 'multiple-choice', question: 'How many books are in the Bible?', options: ['50', '56', '66', '76'], correctAnswer: 2, explanation: 'The Bible has 66 books' },
    { id: 'bible_beg_12', subject: 'Bible', difficulty: 'Beginner', type: 'multiple-choice', question: 'What did God give Moses on Mount Sinai?', options: ['Ten Commandments', 'Staff', 'Manna', 'Water'], correctAnswer: 0, explanation: 'God gave Moses the Ten Commandments' },
  ],
  Intermediate: [
    { id: 'bible_int_1', subject: 'Bible', difficulty: 'Intermediate', type: 'multiple-choice', question: 'What is the first book of the Bible?', options: ['Exodus', 'Genesis', 'Leviticus', 'Psalms'], correctAnswer: 1, explanation: 'Genesis is the first book of the Bible' },
    { id: 'bible_int_2', subject: 'Bible', difficulty: 'Intermediate', type: 'multiple-choice', question: 'Who wrote most of the Psalms?', options: ['Moses', 'Solomon', 'David', 'Isaiah'], correctAnswer: 2, explanation: 'David wrote most of the Psalms' },
    { id: 'bible_int_3', subject: 'Bible', difficulty: 'Intermediate', type: 'multiple-choice', question: 'What did John the Baptist eat in the desert?', options: ['Bread and fish', 'Locusts and honey', 'Fruits', 'Manna'], correctAnswer: 1, explanation: 'John the Baptist ate locusts and wild honey' },
    { id: 'bible_int_4', subject: 'Bible', difficulty: 'Intermediate', type: 'multiple-choice', question: 'Who was sold by his brothers into slavery?', options: ['Jacob', 'Joseph', 'Benjamin', 'Judah'], correctAnswer: 1, explanation: 'Joseph was sold into slavery by his brothers' },
    { id: 'bible_int_5', subject: 'Bible', difficulty: 'Intermediate', type: 'multiple-choice', question: 'What is the last book of the Bible?', options: ['Jude', 'Revelation', 'Acts', 'Hebrews'], correctAnswer: 1, explanation: 'Revelation is the last book of the Bible' },
    { id: 'bible_int_6', subject: 'Bible', difficulty: 'Intermediate', type: 'multiple-choice', question: 'Who was the wisest king in the Bible?', options: ['David', 'Saul', 'Solomon', 'Hezekiah'], correctAnswer: 2, explanation: 'Solomon was known for his wisdom' },
    { id: 'bible_int_7', subject: 'Bible', difficulty: 'Intermediate', type: 'multiple-choice', question: 'What did the Israelites eat in the desert?', options: ['Fish', 'Bread', 'Manna', 'Fruit'], correctAnswer: 2, explanation: 'God provided manna for the Israelites' },
    { id: 'bible_int_8', subject: 'Bible', difficulty: 'Intermediate', type: 'multiple-choice', question: 'Who was the mother of Jesus?', options: ['Martha', 'Mary', 'Elizabeth', 'Ruth'], correctAnswer: 1, explanation: 'Mary was the mother of Jesus' },
    { id: 'bible_int_9', subject: 'Bible', difficulty: 'Intermediate', type: 'multiple-choice', question: 'How many plagues did God send to Egypt?', options: ['7', '9', '10', '12'], correctAnswer: 2, explanation: 'God sent 10 plagues to Egypt' },
    { id: 'bible_int_10', subject: 'Bible', difficulty: 'Intermediate', type: 'multiple-choice', question: 'Who was thrown into a lions\' den?', options: ['Daniel', 'David', 'Elijah', 'Elisha'], correctAnswer: 0, explanation: 'Daniel was thrown into a lions\' den' },
  ],
  Advanced: [
    { id: 'bible_adv_1', subject: 'Bible', difficulty: 'Advanced', type: 'multiple-choice', question: 'Who wrote the book of Romans?', options: ['Peter', 'Paul', 'John', 'James'], correctAnswer: 1, explanation: 'Paul wrote the book of Romans' },
    { id: 'bible_adv_2', subject: 'Bible', difficulty: 'Advanced', type: 'multiple-choice', question: 'What is the shortest verse in the Bible?', options: ['Jesus wept', 'God is love', 'Rejoice always', 'Pray without ceasing'], correctAnswer: 0, explanation: '"Jesus wept" (John 11:35) is the shortest verse' },
    { id: 'bible_adv_3', subject: 'Bible', difficulty: 'Advanced', type: 'multiple-choice', question: 'Who succeeded Moses as leader?', options: ['Aaron', 'Caleb', 'Joshua', 'Samuel'], correctAnswer: 2, explanation: 'Joshua succeeded Moses as leader of Israel' },
    { id: 'bible_adv_4', subject: 'Bible', difficulty: 'Advanced', type: 'multiple-choice', question: 'What is the Beatitudes?', options: ['Jesus\' teachings in Sermon on the Mount', 'The Ten Commandments', 'Parables', 'Miracles'], correctAnswer: 0, explanation: 'Beatitudes are blessings in Jesus\' Sermon on the Mount' },
    { id: 'bible_adv_5', subject: 'Bible', difficulty: 'Advanced', type: 'multiple-choice', question: 'Who was the first martyr in the New Testament?', options: ['Stephen', 'Paul', 'Peter', 'James'], correctAnswer: 0, explanation: 'Stephen was the first Christian martyr' },
    { id: 'bible_adv_6', subject: 'Bible', difficulty: 'Advanced', type: 'multiple-choice', question: 'What does the name "Jesus" mean?', options: ['Savior', 'The Lord saves', 'Messiah', 'King'], correctAnswer: 1, explanation: 'Jesus means "The Lord saves"' },
    { id: 'bible_adv_7', subject: 'Bible', difficulty: 'Advanced', type: 'multiple-choice', question: 'Who was Melchizedek?', options: ['King of Salem', 'Prophet', 'Priest', 'Both king and priest'], correctAnswer: 3, explanation: 'Melchizedek was both king of Salem and priest of God' },
    { id: 'bible_adv_8', subject: 'Bible', difficulty: 'Advanced', type: 'multiple-choice', question: 'What was Paul\'s original name?', options: ['Simon', 'Saul', 'Samuel', 'Stephen'], correctAnswer: 1, explanation: 'Paul was originally named Saul' },
    { id: 'bible_adv_9', subject: 'Bible', difficulty: 'Advanced', type: 'multiple-choice', question: 'What is the fruit of the Spirit in Galatians?', options: ['Love, joy, peace...', 'Faith, hope, love', 'Wisdom, knowledge, faith', 'Grace, mercy, truth'], correctAnswer: 0, explanation: 'Galatians 5:22-23 lists love, joy, peace, patience, etc.' },
    { id: 'bible_adv_10', subject: 'Bible', difficulty: 'Advanced', type: 'multiple-choice', question: 'What covenant did God make with Abraham?', options: ['Ten Commandments', 'Promised land and descendants', 'Eternal life', 'Kingdom'], correctAnswer: 1, explanation: 'God promised Abraham land and many descendants' },
  ],
  Expert: [
    { id: 'bible_exp_1', subject: 'Bible', difficulty: 'Expert', type: 'multiple-choice', question: 'What is the Great Commission?', options: ['Ten Commandments', 'Jesus\' command to make disciples', 'Love your neighbor', 'Feed the poor'], correctAnswer: 1, explanation: 'Great Commission is Jesus\' command to make disciples (Matthew 28:19-20)' },
    { id: 'bible_exp_2', subject: 'Bible', difficulty: 'Expert', type: 'multiple-choice', question: 'What is typology in the Bible?', options: ['Study of types', 'Old Testament events foreshadowing New Testament', 'Genres', 'Languages'], correctAnswer: 1, explanation: 'Typology is how OT events foreshadow NT fulfillment' },
    { id: 'bible_exp_3', subject: 'Bible', difficulty: 'Expert', type: 'multiple-choice', question: 'What does "Paraclete" mean?', options: ['Savior', 'Advocate/Helper', 'Teacher', 'Spirit'], correctAnswer: 1, explanation: 'Paraclete means Advocate or Helper (Holy Spirit)' },
    { id: 'bible_exp_4', subject: 'Bible', difficulty: 'Expert', type: 'multiple-choice', question: 'What is the Septuagint?', options: ['Latin Bible', 'Greek translation of OT', 'Hebrew Bible', 'Aramaic Bible'], correctAnswer: 1, explanation: 'Septuagint is Greek translation of Hebrew Bible' },
    { id: 'bible_exp_5', subject: 'Bible', difficulty: 'Expert', type: 'multiple-choice', question: 'What is the Imago Dei?', options: ['God\'s image', 'God\'s name', 'God\'s law', 'God\'s temple'], correctAnswer: 0, explanation: 'Imago Dei is the concept that humans are made in God\'s image' },
    { id: 'bible_exp_6', subject: 'Bible', difficulty: 'Expert', type: 'multiple-choice', question: 'What is eschatology?', options: ['Study of creation', 'Study of end times', 'Study of sin', 'Study of salvation'], correctAnswer: 1, explanation: 'Eschatology is the study of end times' },
    { id: 'bible_exp_7', subject: 'Bible', difficulty: 'Expert', type: 'multiple-choice', question: 'What is the Mosaic Covenant?', options: ['Abraham\'s covenant', 'Law given at Sinai', 'David\'s covenant', 'New covenant'], correctAnswer: 1, explanation: 'Mosaic Covenant is the Law given to Moses at Sinai' },
    { id: 'bible_exp_8', subject: 'Bible', difficulty: 'Expert', type: 'multiple-choice', question: 'What is the Shema?', options: ['Prayer', 'Jewish confession of faith', 'Commandment', 'Blessing'], correctAnswer: 1, explanation: 'Shema is the Jewish confession: "Hear O Israel, the LORD is one"' },
    { id: 'bible_exp_9', subject: 'Bible', difficulty: 'Expert', type: 'multiple-choice', question: 'What is sanctification?', options: ['Being saved', 'Process of becoming holy', 'Justification', 'Glorification'], correctAnswer: 1, explanation: 'Sanctification is the ongoing process of becoming holy' },
    { id: 'bible_exp_10', subject: 'Bible', difficulty: 'Expert', type: 'multiple-choice', question: 'What is the Davidic Covenant?', options: ['Eternal throne promise', 'Ten Commandments', 'Land promise', 'Temple building'], correctAnswer: 0, explanation: 'God promised David an eternal throne/kingdom' },
  ],
  Master: [
    { id: 'bible_mst_1', subject: 'Bible', difficulty: 'Master', type: 'multiple-choice', question: 'What is progressive revelation?', options: ['God revealing truth gradually', 'Ongoing prophecy', 'New revelations', 'Private visions'], correctAnswer: 0, explanation: 'Progressive revelation is God revealing truth gradually throughout history' },
    { id: 'bible_mst_2', subject: 'Bible', difficulty: 'Master', type: 'multiple-choice', question: 'What is the hypostatic union?', options: ['Union of believers', 'Jesus as fully God and man', 'Trinity', 'Church unity'], correctAnswer: 1, explanation: 'Hypostatic union: Jesus is fully God and fully man' },
    { id: 'bible_mst_3', subject: 'Bible', difficulty: 'Master', type: 'multiple-choice', question: 'What is Covenant Theology?', options: ['Framework of biblical covenants', 'Dispensationalism', 'Law vs grace', 'Church structure'], correctAnswer: 0, explanation: 'Covenant Theology interprets Scripture through biblical covenants' },
    { id: 'bible_mst_4', subject: 'Bible', difficulty: 'Master', type: 'multiple-choice', question: 'What is the Masoretic Text?', options: ['Greek OT', 'Hebrew OT text', 'Latin Bible', 'Dead Sea Scrolls'], correctAnswer: 1, explanation: 'Masoretic Text is the authoritative Hebrew Bible text' },
    { id: 'bible_mst_5', subject: 'Bible', difficulty: 'Master', type: 'multiple-choice', question: 'What is the "already/not yet" tension?', options: ['Kingdom present but not fully realized', 'Salvation incomplete', 'Second coming delayed', 'Church age'], correctAnswer: 0, explanation: 'Kingdom is already present but not yet fully realized' },
    { id: 'bible_mst_6', subject: 'Bible', difficulty: 'Master', type: 'multiple-choice', question: 'What is the canon?', options: ['Church law', 'Recognized books of Scripture', 'Doctrine', 'Creed'], correctAnswer: 1, explanation: 'Canon is the recognized books of Scripture' },
    { id: 'bible_mst_7', subject: 'Bible', difficulty: 'Master', type: 'multiple-choice', question: 'What is propitiation?', options: ['Atonement satisfying God\'s wrath', 'Forgiveness', 'Cleansing', 'Redemption'], correctAnswer: 0, explanation: 'Propitiation is Christ\'s sacrifice satisfying God\'s wrath' },
    { id: 'bible_mst_8', subject: 'Bible', difficulty: 'Master', type: 'multiple-choice', question: 'What is textual criticism?', options: ['Bible interpretation', 'Determining original biblical text', 'Literary analysis', 'Bible translation'], correctAnswer: 1, explanation: 'Textual criticism determines the original biblical text' },
    { id: 'bible_mst_9', subject: 'Bible', difficulty: 'Master', type: 'multiple-choice', question: 'What is hermeneutics?', options: ['Bible study', 'Interpretation principles', 'Theology', 'Preaching'], correctAnswer: 1, explanation: 'Hermeneutics is the study of biblical interpretation principles' },
    { id: 'bible_mst_10', subject: 'Bible', difficulty: 'Master', type: 'multiple-choice', question: 'What is the sensus plenior?', options: ['Literal meaning', 'Fuller meaning beyond author\'s intent', 'Allegorical meaning', 'Historical meaning'], correctAnswer: 1, explanation: 'Sensus plenior is the fuller meaning intended by God beyond human author' },
  ],
};

// ===== LANGUAGE ARTS QUESTIONS =====
const LANGUAGE_ARTS_QUESTIONS: QuestionBank['Language Arts'] = {
  Beginner: [
    { id: 'lang_beg_1', subject: 'Language Arts', difficulty: 'Beginner', type: 'multiple-choice', question: 'What is a noun?', options: ['Action word', 'Person/place/thing', 'Describing word', 'Connecting word'], correctAnswer: 1, explanation: 'A noun is a person, place, or thing' },
    { id: 'lang_beg_2', subject: 'Language Arts', difficulty: 'Beginner', type: 'multiple-choice', question: 'What is a verb?', options: ['Name', 'Action word', 'Describing word', 'Connecting word'], correctAnswer: 1, explanation: 'A verb is an action word' },
    { id: 'lang_beg_3', subject: 'Language Arts', difficulty: 'Beginner', type: 'multiple-choice', question: 'Which is a complete sentence?', options: ['Running fast', 'The dog barks', 'After school', 'In the park'], correctAnswer: 1, explanation: 'A complete sentence needs a subject and verb' },
    { id: 'lang_beg_4', subject: 'Language Arts', difficulty: 'Beginner', type: 'multiple-choice', question: 'What is an adjective?', options: ['Action word', 'Name', 'Describing word', 'Connecting word'], correctAnswer: 2, explanation: 'An adjective is a describing word' },
    { id: 'lang_beg_5', subject: 'Language Arts', difficulty: 'Beginner', type: 'multiple-choice', question: 'Which word is a pronoun?', options: ['Run', 'Happy', 'He', 'Quickly'], correctAnswer: 2, explanation: 'Pronouns replace nouns (I, you, he, she, it, etc.)' },
    { id: 'lang_beg_6', subject: 'Language Arts', difficulty: 'Beginner', type: 'multiple-choice', question: 'What punctuation ends a question?', options: ['Period', 'Exclamation mark', 'Question mark', 'Comma'], correctAnswer: 2, explanation: 'Questions end with a question mark (?)' },
    { id: 'lang_beg_7', subject: 'Language Arts', difficulty: 'Beginner', type: 'multiple-choice', question: 'How many vowels are in the English alphabet?', options: ['4', '5', '6', '7'], correctAnswer: 1, explanation: 'There are 5 vowels: A, E, I, O, U' },
    { id: 'lang_beg_8', subject: 'Language Arts', difficulty: 'Beginner', type: 'multiple-choice', question: 'Which word is capitalized correctly?', options: ['tuesday', 'Tuesday', 'TUESDAY', 'tueSday'], correctAnswer: 1, explanation: 'Days of the week are capitalized' },
    { id: 'lang_beg_9', subject: 'Language Arts', difficulty: 'Beginner', type: 'multiple-choice', question: 'What is a synonym?', options: ['Opposite word', 'Similar word', 'Rhyming word', 'Compound word'], correctAnswer: 1, explanation: 'Synonyms are words with similar meanings' },
    { id: 'lang_beg_10', subject: 'Language Arts', difficulty: 'Beginner', type: 'multiple-choice', question: 'Which is the correct plural of "child"?', options: ['Childs', 'Children', 'Childes', 'Childrens'], correctAnswer: 1, explanation: 'The plural of child is children' },
    { id: 'lang_beg_11', subject: 'Language Arts', difficulty: 'Beginner', type: 'multiple-choice', question: 'What do quotation marks indicate?', options: ['A question', 'Someone speaking', 'Emphasis', 'A title'], correctAnswer: 1, explanation: 'Quotation marks show someone speaking or quoted text' },
    { id: 'lang_beg_12', subject: 'Language Arts', difficulty: 'Beginner', type: 'multiple-choice', question: 'Which word is an adverb?', options: ['Happy', 'Run', 'Quickly', 'Dog'], correctAnswer: 2, explanation: 'Adverbs describe verbs and often end in -ly' },
  ],
  Intermediate: [
    { id: 'lang_int_1', subject: 'Language Arts', difficulty: 'Intermediate', type: 'multiple-choice', question: 'What is a metaphor?', options: ['Direct comparison using like/as', 'Comparison without using like/as', 'Exaggeration', 'Rhyme'], correctAnswer: 1, explanation: 'A metaphor is a comparison without using "like" or "as"' },
    { id: 'lang_int_2', subject: 'Language Arts', difficulty: 'Intermediate', type: 'multiple-choice', question: 'What is alliteration?', options: ['Repeated consonant sounds', 'Rhyming words', 'Repeated vowel sounds', 'Onomatopoeia'], correctAnswer: 0, explanation: 'Alliteration is repeating consonant sounds at the beginning of words' },
    { id: 'lang_int_3', subject: 'Language Arts', difficulty: 'Intermediate', type: 'multiple-choice', question: 'What is the subject of this sentence: "The cat jumped"?', options: ['Jumped', 'The', 'Cat', 'The cat'], correctAnswer: 2, explanation: 'The subject is who or what does the action (cat)' },
    { id: 'lang_int_4', subject: 'Language Arts', difficulty: 'Intermediate', type: 'multiple-choice', question: 'What is a compound sentence?', options: ['Very long sentence', 'Two independent clauses joined', 'Sentence with adjectives', 'Question sentence'], correctAnswer: 1, explanation: 'Compound sentences join two independent clauses' },
    { id: 'lang_int_5', subject: 'Language Arts', difficulty: 'Intermediate', type: 'multiple-choice', question: 'What is personification?', options: ['Giving human traits to non-human things', 'Creating characters', 'Describing people', 'Using pronouns'], correctAnswer: 0, explanation: 'Personification gives human qualities to non-human things' },
    { id: 'lang_int_6', subject: 'Language Arts', difficulty: 'Intermediate', type: 'multiple-choice', question: 'Which is a complex sentence?', options: ['I ran fast', 'I ran fast and jumped high', 'When I ran, I felt tired', 'I ran'], correctAnswer: 2, explanation: 'Complex sentences have independent and dependent clauses' },
    { id: 'lang_int_7', subject: 'Language Arts', difficulty: 'Intermediate', type: 'multiple-choice', question: 'What is onomatopoeia?', options: ['Rhyming', 'Sound words (buzz, crash)', 'Repetition', 'Metaphor'], correctAnswer: 1, explanation: 'Onomatopoeia are words that sound like what they mean' },
    { id: 'lang_int_8', subject: 'Language Arts', difficulty: 'Intermediate', type: 'multiple-choice', question: 'What is the past tense of "run"?', options: ['Runned', 'Ran', 'Running', 'Runs'], correctAnswer: 1, explanation: 'The past tense of run is ran' },
    { id: 'lang_int_9', subject: 'Language Arts', difficulty: 'Intermediate', type: 'multiple-choice', question: 'What is an antonym?', options: ['Similar word', 'Opposite word', 'Rhyming word', 'Compound word'], correctAnswer: 1, explanation: 'Antonyms are words with opposite meanings' },
    { id: 'lang_int_10', subject: 'Language Arts', difficulty: 'Intermediate', type: 'multiple-choice', question: 'What is the main idea?', options: ['First sentence', 'Most important point', 'Longest paragraph', 'Conclusion'], correctAnswer: 1, explanation: 'Main idea is the most important point of a text' },
  ],
  Advanced: [
    { id: 'lang_adv_1', subject: 'Language Arts', difficulty: 'Advanced', type: 'multiple-choice', question: 'What is a gerund?', options: ['Verb ending in -ing used as noun', 'Past tense verb', 'Adjective', 'Adverb'], correctAnswer: 0, explanation: 'A gerund is a verb ending in -ing used as a noun' },
    { id: 'lang_adv_2', subject: 'Language Arts', difficulty: 'Advanced', type: 'multiple-choice', question: 'What is foreshadowing?', options: ['Flashback', 'Hinting at future events', 'Description', 'Conflict'], correctAnswer: 1, explanation: 'Foreshadowing hints at events that will happen later' },
    { id: 'lang_adv_3', subject: 'Language Arts', difficulty: 'Advanced', type: 'multiple-choice', question: 'What is an independent clause?', options: ['Incomplete thought', 'Complete thought that can stand alone', 'Question', 'Fragment'], correctAnswer: 1, explanation: 'Independent clause is a complete thought that can stand alone' },
    { id: 'lang_adv_4', subject: 'Language Arts', difficulty: 'Advanced', type: 'multiple-choice', question: 'What is irony?', options: ['Humor', 'Opposite of what\'s expected', 'Repetition', 'Rhyme'], correctAnswer: 1, explanation: 'Irony is when the outcome is opposite of what\'s expected' },
    { id: 'lang_adv_5', subject: 'Language Arts', difficulty: 'Advanced', type: 'multiple-choice', question: 'What is a thesis statement?', options: ['First sentence', 'Main argument', 'Conclusion', 'Evidence'], correctAnswer: 1, explanation: 'Thesis statement is the main argument of an essay' },
    { id: 'lang_adv_6', subject: 'Language Arts', difficulty: 'Advanced', type: 'multiple-choice', question: 'What is hyperbole?', options: ['Comparison', 'Exaggeration', 'Understatement', 'Rhyme'], correctAnswer: 1, explanation: 'Hyperbole is extreme exaggeration for effect' },
    { id: 'lang_adv_7', subject: 'Language Arts', difficulty: 'Advanced', type: 'multiple-choice', question: 'What is a participle?', options: ['Noun', 'Verb form used as adjective', 'Adverb', 'Conjunction'], correctAnswer: 1, explanation: 'Participles are verb forms used as adjectives' },
    { id: 'lang_adv_8', subject: 'Language Arts', difficulty: 'Advanced', type: 'multiple-choice', question: 'What is symbolism?', options: ['Literal meaning', 'Object representing something else', 'Description', 'Plot'], correctAnswer: 1, explanation: 'Symbolism is using objects to represent ideas' },
    { id: 'lang_adv_9', subject: 'Language Arts', difficulty: 'Advanced', type: 'multiple-choice', question: 'What is a subordinate clause?', options: ['Main clause', 'Dependent clause', 'Complete sentence', 'Fragment'], correctAnswer: 1, explanation: 'Subordinate clauses are dependent and cannot stand alone' },
    { id: 'lang_adv_10', subject: 'Language Arts', difficulty: 'Advanced', type: 'multiple-choice', question: 'What is tone in literature?', options: ['Author\'s attitude', 'Volume', 'Rhyme scheme', 'Setting'], correctAnswer: 0, explanation: 'Tone is the author\'s attitude toward the subject' },
  ],
  Expert: [
    { id: 'lang_exp_1', subject: 'Language Arts', difficulty: 'Expert', type: 'multiple-choice', question: 'What is an oxymoron?', options: ['Contradiction in terms', 'Exaggeration', 'Comparison', 'Rhyme'], correctAnswer: 0, explanation: 'An oxymoron combines contradictory terms (e.g., "jumbo shrimp")' },
    { id: 'lang_exp_2', subject: 'Language Arts', difficulty: 'Expert', type: 'multiple-choice', question: 'What is the subjunctive mood?', options: ['Expressing facts', 'Expressing wishes/hypotheticals', 'Asking questions', 'Giving commands'], correctAnswer: 1, explanation: 'Subjunctive mood expresses wishes, suggestions, or hypotheticals' },
    { id: 'lang_exp_3', subject: 'Language Arts', difficulty: 'Expert', type: 'multiple-choice', question: 'What is zeugma?', options: ['One word governing multiple clauses', 'Alliteration', 'Metaphor', 'Personification'], correctAnswer: 0, explanation: 'Zeugma uses one word to modify two or more words in different ways' },
    { id: 'lang_exp_4', subject: 'Language Arts', difficulty: 'Expert', type: 'multiple-choice', question: 'What is epistrophe?', options: ['Repeating words at beginning', 'Repeating words at end', 'Alliteration', 'Rhyme'], correctAnswer: 1, explanation: 'Epistrophe repeats words at the end of successive clauses' },
    { id: 'lang_exp_5', subject: 'Language Arts', difficulty: 'Expert', type: 'multiple-choice', question: 'What is verisimilitude?', options: ['Truth', 'Appearance of being true/real', 'Falsehood', 'Exaggeration'], correctAnswer: 1, explanation: 'Verisimilitude is the appearance of being true or real in literature' },
    { id: 'lang_exp_6', subject: 'Language Arts', difficulty: 'Expert', type: 'multiple-choice', question: 'What is an appositive?', options: ['Verb phrase', 'Noun/phrase renaming another noun', 'Adjective', 'Adverb'], correctAnswer: 1, explanation: 'Appositive is a noun or phrase that renames another noun beside it' },
    { id: 'lang_exp_7', subject: 'Language Arts', difficulty: 'Expert', type: 'multiple-choice', question: 'What is anaphora?', options: ['Repetition at beginning of clauses', 'Repetition at end', 'Rhyme', 'Alliteration'], correctAnswer: 0, explanation: 'Anaphora repeats words at the beginning of successive clauses' },
    { id: 'lang_exp_8', subject: 'Language Arts', difficulty: 'Expert', type: 'multiple-choice', question: 'What is synecdoche?', options: ['Part representing whole', 'Exaggeration', 'Comparison', 'Rhyme'], correctAnswer: 0, explanation: 'Synecdoche uses a part to represent the whole or vice versa' },
    { id: 'lang_exp_9', subject: 'Language Arts', difficulty: 'Expert', type: 'multiple-choice', question: 'What is chiasmus?', options: ['Parallelism', 'Reversed parallel structure', 'Rhyme', 'Repetition'], correctAnswer: 1, explanation: 'Chiasmus reverses the structure in parallel phrases' },
    { id: 'lang_exp_10', subject: 'Language Arts', difficulty: 'Expert', type: 'multiple-choice', question: 'What is litotes?', options: ['Exaggeration', 'Understatement using double negative', 'Direct statement', 'Question'], correctAnswer: 1, explanation: 'Litotes is understatement using double negatives for effect' },
  ],
  Master: [
    { id: 'lang_mst_1', subject: 'Language Arts', difficulty: 'Master', type: 'multiple-choice', question: 'What is polysyndeton?', options: ['Using many conjunctions', 'Omitting conjunctions', 'Repetition', 'Rhyme'], correctAnswer: 0, explanation: 'Polysyndeton uses multiple conjunctions in close succession' },
    { id: 'lang_mst_2', subject: 'Language Arts', difficulty: 'Master', type: 'multiple-choice', question: 'What is asyndeton?', options: ['Using many conjunctions', 'Omitting conjunctions', 'Parallelism', 'Metaphor'], correctAnswer: 1, explanation: 'Asyndeton omits conjunctions between clauses' },
    { id: 'lang_mst_3', subject: 'Language Arts', difficulty: 'Master', type: 'multiple-choice', question: 'What is metonymy?', options: ['Metaphor', 'Substituting name of attribute for thing', 'Exaggeration', 'Rhyme'], correctAnswer: 1, explanation: 'Metonymy substitutes an attribute or associated thing for the name' },
    { id: 'lang_mst_4', subject: 'Language Arts', difficulty: 'Master', type: 'multiple-choice', question: 'What is the Sapir-Whorf hypothesis?', options: ['Language shapes thought', 'Thought shapes language', 'Universal grammar', 'Language evolution'], correctAnswer: 0, explanation: 'Sapir-Whorf hypothesis: language influences how we think' },
    { id: 'lang_mst_5', subject: 'Language Arts', difficulty: 'Master', type: 'multiple-choice', question: 'What is a sibilant?', options: ['Vowel sound', 'Hissing consonant sound', 'Stop consonant', 'Nasal sound'], correctAnswer: 1, explanation: 'Sibilants are hissing sounds like s, z, sh' },
    { id: 'lang_mst_6', subject: 'Language Arts', difficulty: 'Master', type: 'multiple-choice', question: 'What is enjambment?', options: ['End-stopped line', 'Line break mid-phrase', 'Rhyme', 'Meter'], correctAnswer: 1, explanation: 'Enjambment is when a sentence continues past a line break' },
    { id: 'lang_mst_7', subject: 'Language Arts', difficulty: 'Master', type: 'multiple-choice', question: 'What is the Great Vowel Shift?', options: ['Modern pronunciation change', 'Historical English vowel change', 'Accent variation', 'Dialect difference'], correctAnswer: 1, explanation: 'Great Vowel Shift changed English vowel pronunciation (1400-1700)' },
    { id: 'lang_mst_8', subject: 'Language Arts', difficulty: 'Master', type: 'multiple-choice', question: 'What is a caesura?', options: ['Line break', 'Pause in middle of line', 'Rhyme', 'Stanza break'], correctAnswer: 1, explanation: 'Caesura is a pause or break in the middle of a poetic line' },
    { id: 'lang_mst_9', subject: 'Language Arts', difficulty: 'Master', type: 'multiple-choice', question: 'What is the Oxford comma?', options: ['Period', 'Serial comma before "and"', 'Semicolon', 'Colon'], correctAnswer: 1, explanation: 'Oxford comma is the serial comma before "and" in a list' },
    { id: 'lang_mst_10', subject: 'Language Arts', difficulty: 'Master', type: 'multiple-choice', question: 'What is an unreliable narrator?', options: ['Omniscient narrator', 'Narrator whose credibility is compromised', 'Third-person narrator', 'Absent narrator'], correctAnswer: 1, explanation: 'Unreliable narrator\'s credibility is questionable or biased' },
  ],
};

// Generate worksheet with 10 random questions from the difficulty level
export function generateWorksheet(
  subject: SubjectType,
  difficulty: DifficultyLevel
): WorksheetQuestion[] {
  const questionBank: Record<string, any> = {
    'Math': MATH_QUESTIONS,
    'Science': SCIENCE_QUESTIONS,
    'History': HISTORY_QUESTIONS,
    'Bible': BIBLE_QUESTIONS,
    'Language Arts': LANGUAGE_ARTS_QUESTIONS,
  };

  const subjectQuestions = questionBank[subject];
  if (!subjectQuestions || !subjectQuestions[difficulty]) {
    console.error(`No questions found for ${subject} at ${difficulty} level`);
    return [];
  }

  const questions = subjectQuestions[difficulty];

  // Shuffle and take 10 questions
  const shuffled = [...questions].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, 10);
}

// Calculate stars based on score percentage
export function calculateStars(scorePercentage: number): number {
  if (scorePercentage >= 90) return 5;
  if (scorePercentage >= 80) return 4;
  if (scorePercentage >= 70) return 3;
  if (scorePercentage >= 60) return 2;
  if (scorePercentage >= 50) return 1;
  return 0;
}
